import type {Metadata} from "next";
import {ReactNode} from "react";
import Header from "@/components/layout/Header";
import "bootstrap/scss/bootstrap.scss"
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main className="container">
                    {children}
                </main>
            </body>
        </html>
    );
}
